<?php

use Illuminate\Database\Seeder;

class RestaurantsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('restaurants')->insert([
        [
            'name' => 'Greek restaurant',
            'notes' => 'Very tasty Greek restaurant',
            'priceRange' => '4',
            'genre' => 'greek',
            'address' => '55 Boul. Gouin West',
            'city' => 'Montreal',
            'postalCode' => 'H3M1T5',
            'latitude' => '45.5419107',
            'longitude' => '-73.7059562',   
            'user_id' => '1',
            'image' => 'http://img.sndimg.com/food/image/upload/fl_progressive,w_308,h_231,c_fill,q_92/v1/img/recipes/66/59/6/pic4iSLGv.jpg',
        ],
        [   'name' => 'Tamil cuisine',
            'notes' => 'Fine Tamil cuisine',
            'priceRange' => '1',
            'genre' => 'tamil',
            'address' => '454 Boul. de Maisonneuve West',
            'city' => 'Montreal',
            'postalCode' => 'H3Z3G4',
            'latitude' => '45.488153',
            'longitude' => '-73.588082',   
            'user_id' => '1',
            'image' => 'http://www.rovingturtle.com/static//media/contentfrontimages/Food_Talk_-_Tamil_Nadu.jpg',
        ],
        [   'name' => 'Italian restaurant',
            'notes' => 'Pizza, Pasta, etc.',
            'priceRange' => '4',
            'genre' => 'italian',
            'address' => '850 Boul. Lacordaire',
            'city' => 'Montreal',
            'postalCode' => 'H1P0J4',
            'latitude' => '45.587491',
            'longitude' => '-73.596949',   
            'user_id' => '1',
            'image' => 'http://www.e-buono.com/wp-content/uploads/2016/07/italian-ceasar-pasta.jpg',
        ],
        [   'name' => 'Curry in a hurry',
            'notes' => 'Curry fast',
            'priceRange' => '1',
            'genre' => 'indian',
            'address' => '1 de la Montagne',
            'city' => 'Montreal',
            'postalCode' => 'H3C4T7',
            'latitude' => '45.495908',
            'longitude' => ' -73.570755',   
            'user_id' => '1',
            'image' => 'http://www.36spices.com/english/gallery/images/24%20mix%20seafood%20curry1250.jpg',
        ],
        [
            'name' => 'Fish and chips',
            'notes' => 'London\'s finest',
            'priceRange' => '3',
            'genre' => 'british',
            'address' => '2000 rue du Fort',
            'city' => 'Montreal',
            'postalCode' => 'H3H2C4',
            'latitude' => '45.491853',
            'longitude' => '-73.581595',   
            'user_id' => '1', 
            'image' => 'http://static01.mediaite.com/med/wp-content/uploads/2013/09/fish-and-chips.jpg',
        ],
        [
            'name' => 'Mercuri Montreal',
            'notes' => 'Located in Old Montreal',
            'priceRange' => '4',
            'genre' => 'Italian',
            'address' => '645 Wellington St',
            'city' => 'Montreal',
            'postalCode' => 'H3C1T2',
            'latitude' => '45.4986526000',
            'longitude' => '-73.5553183000',   
            'user_id' => '1',
            'image' => 'http://img.sndimg.com/food/image/upload/fl_progressive,w_308,h_231,c_fill,q_92/v1/img/recipes/66/59/6/pic4iSLGv.jpg',
        ],
        [   'name' => 'Montreal Poutine',
            'notes' => 'Great Montreal Poutine',
            'priceRange' => '2',
            'genre' => 'quebecois',
            'address' => '181 Rue Saint Paul Est',
            'city' => 'Montreal',
            'postalCode' => 'H2Y1G8',
            'latitude' => '45.5072440000',
            'longitude' => '-73.5528430000',   
            'user_id' => '1',
            'image' => 'http://www.rovingturtle.com/static//media/contentfrontimages/Food_Talk_-_Tamil_Nadu.jpg',
        ],
        [   'name' => 'Namaste Montreal',
            'notes' => 'Indian cuisine at its finest',
            'priceRange' => '1',
            'genre' => 'Indian',
            'address' => '212 Milton St',
            'city' => 'Montreal',
            'postalCode' => 'H2X1V6',
            'latitude' => '45.5107526000',
            'longitude' => '-73.5725224000',   
            'user_id' => '1',
            'image' => 'http://www.e-buono.com/wp-content/uploads/2016/07/italian-ceasar-pasta.jpg',
        ],
        [   'name' => 'Brisket Montreal',
            'notes' => 'Classic Canadian restaurant',
            'priceRange' => '2',
            'genre' => 'Canadian',
            'address' => '1093 Cote Du Beaver-Hall',
            'city' => 'Montreal',
            'postalCode' => 'H2Z1W7',
            'latitude' => '45.5028990000',
            'longitude' => '-73.5656990000',   
            'user_id' => '1',
            'image' => 'http://www.36spices.com/english/gallery/images/24%20mix%20seafood%20curry1250.jpg',
        ],
        [
            'name' => 'Thursdays Montreal',
            'notes' => 'In the heart of downtown Montreal',
            'priceRange' => '3',
            'genre' => 'french',
            'address' => '1449 Rue Crescent',
            'city' => 'Montreal',
            'postalCode' => 'H3G2A9',
            'latitude' => '45.491853',
            'longitude' => '-73.581595',   
            'user_id' => '1', 
            'image' => 'http://static01.mediaite.com/med/wp-content/uploads/2013/09/fish-and-chips.jpg',
        ],
        [
            'name' => 'Smokys Montreal',
            'notes' => 'Classic Montreal Deli',
            'priceRange' => '2',
            'genre' => 'Deli',
            'address' => '1029 Rue Du Marche-Central',
            'city' => 'Montreal',
            'postalCode' => 'H4N1J8',
            'latitude' => '45.5349370000',
            'longitude' => '-73.6586000000',   
            'user_id' => '1',
            'image' => 'http://img.sndimg.com/food/image/upload/fl_progressive,w_308,h_231,c_fill,q_92/v1/img/recipes/66/59/6/pic4iSLGv.jpg',
        ],
        [   'name' => 'B Montreal',
            'notes' => 'Sandwiches, coffee, etc.',
            'priceRange' => '2',
            'genre' => 'Cafe',
            'address' => '1207, rue Rachel E',
            'city' => 'Montreal',
            'postalCode' => 'H2X2J8',
            'latitude' => '45.5266553000',
            'longitude' => '-73.5757008000',   
            'user_id' => '1',
            'image' => 'http://www.rovingturtle.com/static//media/contentfrontimages/Food_Talk_-_Tamil_Nadu.jpg',
        ],
        [   'name' => 'Fusion Montreal',
            'notes' => 'Perfect for all of your dessert needs.',
            'priceRange' => '1',
            'genre' => 'Desserts',
            'address' => '1000 Rue De La Gauchetière Ouest',
            'city' => 'Montreal',
            'postalCode' => 'H3B0J4',
            'latitude' => '45.4983800000',
            'longitude' => '-73.5670870000',   
            'user_id' => '1',
            'image' => 'http://www.e-buono.com/wp-content/uploads/2016/07/italian-ceasar-pasta.jpg',
        ],
        [   'name' => 'Le Montréal',
            'notes' => 'French cuisine right at the Montreal Casino',
            'priceRange' => '1',
            'genre' => 'French',
            'address' => '1 Ave Du Casino',
            'city' => 'Montreal',
            'postalCode' => 'H3C4W7',
            'latitude' => '45.5056160000',
            'longitude' => '-73.5259540000',   
            'user_id' => '1',
            'image' => 'http://www.36spices.com/english/gallery/images/24%20mix%20seafood%20curry1250.jpg',
        ],
        [
            'name' => 'Montréal Café',
            'notes' => 'Cafe in the heart of the famous Plateau borough',
            'priceRange' => '1',
            'genre' => 'coffee',
            'address' => '1546 Ave Laurier E',
            'city' => 'Montreal',
            'postalCode' => 'H2J3W5',
            'latitude' => '45.5345280000',
            'longitude' => '-73.5826410000',   
            'user_id' => '1', 
            'image' => 'http://static01.mediaite.com/med/wp-content/uploads/2013/09/fish-and-chips.jpg',
        ],
        [
            'name' => 'Renaissance Montreal',
            'notes' => 'Located in the Golden Square Mile',
            'priceRange' => '1',
            'genre' => 'canadian',
            'address' => '1250 Boulevard Robert-Bourassa',
            'city' => 'Montreal',
            'postalCode' => 'H3B1M7',
            'latitude' => '45.5027610000',
            'longitude' => '-73.5693020000',   
            'user_id' => '1',
            'image' => 'http://img.sndimg.com/food/image/upload/fl_progressive,w_308,h_231,c_fill,q_92/v1/img/recipes/66/59/6/pic4iSLGv.jpg',
        ],
        [   'name' => 'Churros Montréal',
            'notes' => 'Latin american classics',
            'priceRange' => '1',
            'genre' => 'latin american',
            'address' => '7497 Rue St-Hubert',
            'city' => 'Montreal',
            'postalCode' => 'H2R2N3',
            'latitude' => '45.5429010000',
            'longitude' => '-73.6177540000',   
            'user_id' => '1',
            'image' => 'http://www.rovingturtle.com/static//media/contentfrontimages/Food_Talk_-_Tamil_Nadu.jpg',
        ],
        [   'name' => 'Pizza Montréal',
            'notes' => 'Great pizza at a great price',
            'priceRange' => '1',
            'genre' => 'pizza',
            'address' => '1534 Rue Jarry E',
            'city' => 'Montreal',
            'postalCode' => 'H2E1V6',
            'latitude' => '45.5517860000',
            'longitude' => '-73.6200940000',   
            'user_id' => '2',
            'image' => 'http://www.e-buono.com/wp-content/uploads/2016/07/italian-ceasar-pasta.jpg',
        ],
        [   'name' => 'Bier Markt Montréal',
            'notes' => 'Canadian bar food',
            'priceRange' => '3',
            'genre' => 'Canadian',
            'address' => '1221 Blvd René-Lévesque Ouest',
            'city' => 'Montreal',
            'postalCode' => 'H3G1T1',
            'latitude' => '45.4973632000',
            'longitude' => '-73.5717572000',   
            'user_id' => '2',
            'image' => 'http://www.36spices.com/english/gallery/images/24%20mix%20seafood%20curry1250.jpg',
        ],
        [
            'name' => 'Folies de Montréal',
            'notes' => 'Great place for classic hamburgers',
            'priceRange' => '4',
            'genre' => 'burgers',
            'address' => '701 Avenue Du Mont-Royal East',
            'city' => 'Montreal',
            'postalCode' => 'H2J1W5',
            'latitude' => '45.5252860000',
            'longitude' => '-73.5817580000',   
            'user_id' => '2', 
            'image' => 'http://static01.mediaite.com/med/wp-content/uploads/2013/09/fish-and-chips.jpg',
        ]
        ]);
    }
}
